In [15]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [16]:
import time

a=np.random.rand(1000000)
b=np.random.rand(1000000)

tic=time.time()
c=np.dot(a,b)
toc=time.time()

print(c)
print('Verctrozed version:'+ str(1000*(toc-tic))+'ms')

c=0
tic=time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc=time.time()

print('For loop:'+ str(1000*(toc-tic))+'ms')
print(c)

249696.00664245122
Verctrozed version:0.942230224609375ms
For loop:456.8495750427246ms
249696.00664244563


In [17]:
b=np.random.rand

In [18]:
tic=time.time()

In [19]:
c=np.dot

In [21]:
A=np.array([[1,2],[3,4]])

In [22]:
A

array([[1, 2],
       [3, 4]])

In [28]:
B=A.sum(axis=0)

In [29]:
A.sum(axis=1)

array([3, 7])

In [30]:
A/B

array([[0.25      , 0.33333333],
       [0.75      , 0.66666667]])

In [31]:
A/B.reshape(1,2)

array([[0.25      , 0.33333333],
       [0.75      , 0.66666667]])

In [32]:
C=np.random.rand(8)

In [33]:
C

array([0.57704588, 0.38863769, 0.10709587, 0.14635841, 0.95901177,
       0.56856887, 0.8216066 , 0.25064077])

In [35]:
C.shape

(8,)

In [36]:
print(C.T)

[0.57704588 0.38863769 0.10709587 0.14635841 0.95901177 0.56856887
 0.8216066  0.25064077]


In [37]:
np.dot(C,C.T)

2.4977438484009795

In [38]:
D=np.random.rand(8,1)

In [39]:
D

array([[0.8731072 ],
       [0.81000938],
       [0.59597819],
       [0.37318689],
       [0.75501225],
       [0.8170471 ],
       [0.37870304],
       [0.37696474]])

In [41]:
print(D.T)

[[0.8731072  0.81000938 0.59597819 0.37318689 0.75501225 0.8170471
  0.37870304 0.37696474]]


In [44]:
m=np.dot(D,D.T)

In [45]:
m

array([[0.76231618, 0.70722502, 0.52035285, 0.32583216, 0.65920663,
        0.7133697 , 0.33064835, 0.32913062],
       [0.70722502, 0.6561152 , 0.48274793, 0.30228488, 0.61156701,
        0.66181582, 0.30675301, 0.30534497],
       [0.52035285, 0.48274793, 0.35519001, 0.22241125, 0.44997083,
        0.48694225, 0.22569875, 0.22466276],
       [0.32583216, 0.30228488, 0.22241125, 0.13926845, 0.28176067,
        0.30491126, 0.14132701, 0.1406783 ],
       [0.65920663, 0.61156701, 0.44997083, 0.28176067, 0.57004349,
        0.61688057, 0.28592543, 0.28461299],
       [0.7133697 , 0.66181582, 0.48694225, 0.30491126, 0.61688057,
        0.66756597, 0.30941822, 0.30799794],
       [0.33064835, 0.30675301, 0.22569875, 0.14132701, 0.28592543,
        0.30941822, 0.14341599, 0.14275769],
       [0.32913062, 0.30534497, 0.22466276, 0.1406783 , 0.28461299,
        0.30799794, 0.14275769, 0.14210241]])

In [46]:
m[2][3]

0.2224112466666853

In [47]:
a = np.random.randn(2, 3) 
b = np.random.randn(2, 1)
c = a + b

In [48]:
c.shape

(2, 3)

In [49]:
a = np.random.randn(4, 3) 
b = np.random.randn(3, 2) 
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [50]:
a = np.random.randn(4, 3)

In [51]:
b = np.random.randn(3, 2)

In [52]:
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [53]:
a

array([[ 0.10807716,  0.01301015,  1.34620187],
       [ 0.09349151,  0.1009482 ,  1.37173572],
       [ 1.02397402, -1.2704375 , -1.18425472],
       [-0.48717238,  0.10156077,  0.26980646]])

In [54]:
b

array([[ 1.93424583, -0.46963583],
       [ 1.82698416,  1.47331334],
       [ 0.78412585,  0.10385282]])

In [55]:
np.dot(a,b)

array([[ 1.28840882,  0.10821798],
       [ 1.44087977,  0.24728   ],
       [-1.26905645, -2.4756356 ],
       [-0.54519903,  0.4064446 ]])

In [57]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)

In [58]:
c.shape

(12288, 45)

In [61]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [62]:
a

array([[-0.23349602,  0.11202922,  0.66414304],
       [ 1.67572078,  1.09507403, -0.16410088],
       [ 0.94891541,  0.97409611, -0.78810865]])

In [63]:
b

array([[-1.50127351],
       [-1.03389279],
       [-0.65372834]])

In [64]:
c

array([[ 0.35054139, -0.1681865 , -0.99706035],
       [-1.73251564, -1.13218915,  0.16966272],
       [-0.62033289, -0.63679423,  0.51520896]])

In [65]:

A=np.array([1,2,3])
B=np.array([2,3,4])

In [66]:
mul = np.multiply(A,B)

In [67]:
mul

array([ 2,  6, 12])

In [68]:
np.outer(A,B)

array([[ 2,  3,  4],
       [ 4,  6,  8],
       [ 6,  9, 12]])